#:kivy 2.3.0

<RoundedButton@Button>:
    player: 0 # 0 = neutral, 1 = player 1 (red), 2 = player 2 (blue)
    background_color: 0, 0, 0, 0
    color: 1, 1, 1, 1
    font_size: '18sp'
    font_name: 'pi_client/assets/fonts/Inter/static/Inter_18pt-Bold.ttf'
    size_hint: None, None
    size: 200, 50
    background_normal: 'pi_client/assets/transparent.png'
    background_down: 'pi_client/assets/transparent.png'
    background_disabled_normal: 'pi_client/assets/transparent.png'
    background_disabled_down: 'pi_client/assets/transparent.png'
    border: (0, 0, 0, 0)
    text: root.text.title() if hasattr(root, 'text') and root.text else ''
    canvas.before:
        Color:
            rgba: (0.2, 0.2, 0.2, 1) if self.disabled else (0.3, 0.3, 0.3, 1)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [10] 