<HeaderWidget>:
    height: '86px'
    size_hint_y: None
    canvas.before:
        Color:
            rgba: 0.2, 0.2, 0.2, 1
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        text: root.title
        color: 1, 1, 1, 1
        font_size: '20sp'
        size_hint_x: None
        width: self.texture_size[0]
        pos_hint: {'right': 1, 'center_y': 0.5}
        padding: 10, 0 