<PlayerStartButton@Button>:
    background_normal: ''
    background_color: 0, 0, 0, 0
    color: 1, 1, 1, 1
    font_size: '24sp'
    font_name: 'Inter_18pt-Bold.ttf'
    size_hint: None, None
    size: '200dp', '48dp'
    canvas.before:
        Color:
            rgba: (0.2, 0.2, 0.2, 1) if self.state == 'normal' else (0.3, 0.3, 0.3, 1)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [10,] 