"""Initial migration

Revision ID: fcdbf6276fcf
Revises: 
Create Date: 2025-06-07 18:36:39.760706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcdbf6276fcf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('active_player_id', sa.Integer(), nullable=True),
    sa.Column('game_phase', sa.String(), nullable=True),
    sa.Column('status_message', sa.String(), nullable=True),
    sa.Column('game_timer_status', sa.String(), nullable=True),
    sa.Column('game_timer_start_time', sa.Float(), nullable=True),
    sa.Column('game_timer_elapsed_display', sa.String(), nullable=True),
    sa.Column('turn_segment_start_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('primary_score', sa.Integer(), nullable=True),
    sa.Column('secondary_score', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('cp', sa.Integer(), nullable=True),
    sa.Column('deployment_roll', sa.Integer(), nullable=True),
    sa.Column('first_turn_roll', sa.Integer(), nullable=True),
    sa.Column('player_elapsed_time_seconds', sa.Float(), nullable=True),
    sa.Column('player_time_display', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('primary_score', sa.Integer(), nullable=True),
    sa.Column('secondary_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', 'round_number', name='_game_player_round_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turn')
    op.drop_table('player')
    op.drop_table('game')
    # ### end Alembic commands ###
