#:kivy 2.2.1
#:import UI_STRINGS pi_client.strings.UI_STRINGS
#:include pi_client/widgets/button_styles.kv
 #:include pi_client/widgets/gear_button.kv
 
<SplashScreen>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            source: 'pi_client/assets/background.png'
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: 'vertical'
        # Header
        HeaderWidget:
            id: header
            title: UI_STRINGS['splash']['title']

        BoxLayout:
            orientation: 'vertical'
            padding: '20dp'
            spacing: '10dp'
            # Loading Status
            Label:
                id: loading_status
                text: root.loading_status
                font_size: '20sp'
                size_hint_y: None
                height: '30dp'
                color: 1, 1, 1, 1

            # Error Message
            Label:
                id: error_label
                text: root.error_message
                font_size: '16sp'
                size_hint_y: None
                height: '30dp'
                color: 1, 0, 0, 1
                opacity: 1 if root.error_message else 0

        # Start Button
        RoundedButton:
            text: 'Start'
            size_hint_y: None
            height: '50dp'
            width: '800dp'
            disabled: not root.start_enabled
            on_release: root.manager.transition.direction = 'left'; root.manager.current = 'name_entry' 